#!/bin/sh

source $XDG_CONFIG_HOME/panel/config
source $XDG_CONFIG_HOME/panel/colors

panel_workspaces() {
	desktop=1
	ws=""
	IFS=':' read -a array <<< $1
	for item in "${array[@]}"
	do
		name=${item#?}
		if [ "$item" == "LT" ]
		then
			ws="${ws}%{S+}"
		else
			desk=""
			case $item in
				O*) # focused occupied
					desk="%{R} ${name} %{R}"
				;;
				F*) # focused free
					desk="%{R} ${name} %{R}"
				;;
				U*) # focused urgent
					desk="%{R} ${name} %{R}"
				;;
				o*) # occupied
					desk=" ${name} "
				;;
				f*) # free
					desk=" ${name} "
				;;
				u*) # urgent
					desk=" {$name} "
				;;
			esac

			if [ "$desk" != "" ]
			then
				ws="${ws}%{A:bspc desktop -f ^$desktop:}${desk}%{A}"
				desktop=$((desktop+1))
			fi
		fi
	done
	ws="${ws}${S0}"
	echo "${ws}"
}

panel_title() {
	title=""
	case $(bspc query -M -m focused) in
		0x00400002)
			title="%{S0}"
		;;
		0x00400004)
			title="%{S1}"
		;;
		esac
	echo "${title}$1${S0}"
}

panel_sound() {
	volume=$(amixer -q | grep -A5 Master | grep '%' | cut -d'[' -f2 | cut -d'%' -f1)
	if [ "$volume" == "0" ]
	then
		icon="\ufc5d" #Mute
	elif ((0 < volume && volume <= 33))
	then
		icon="\ufa7e" #No Soundbar
	elif ((33 < volume && volume <= 66))
	then
		icon="\ufa7f" #One Soundbar
	else
		icon="\ufa7d" #Three Soundbars
	fi	
	echo "%{A4:amixer set Master 10%+ > /dev/null:}%{A5:amixer set Master 10%- > /dev/null:}%{A:$XDG_CONFIG_HOME/panel/popup_sound &:}%{B#ffC1C7BF}%{F#fff3f3f3} $icon %{F-}%{B-}%{A}%{A}%{A}"
}

panel_hostname() {
	echo "%{A:$XDG_CONFIG_HOME/panel/popup_power &:}%{B#ff93a1a1}%{F#fff3f3f3} $(hostname) %{F-}%{B-}%{A}"
}

panel_clock() {
	echo "%{A:$XDG_CONFIG_HOME/panel/popup_cal &:}%{B#ff657b83}%{F#fff3f3f3} $(date +'%a %-I:%M %p') %{A}%{F-}%{B-}"
}

watch_workspaces() {
	bspc subscribe | while read line
	do
		panel_workspaces $line > $WORKSPACES_FILE
		print_panel
	done
}

watch_title() {
    xtitle -s | while read line
    do
        panel_title "$line" > $TITLE_FILE
        print_panel
    done
}

watch_sound() {
	pactl subscribe | grep --line-buffered "'change' on sink" | while read line
	do
		panel_sound > $SOUND_FILE
		print_panel
	done
}

watch_clock() {
	while true
	do
		sleep $(expr 60 - $(date +%S))
		panel_clock > $CLOCK_FILE
		print_panel
	done
}

# print to panel
print_panel() {
	echo -e "%{l}$(cat $WORKSPACES_FILE)" \
		"%{c}$(cat $TITLE_FILE)" \
		"%{Sl}%{r}$(cat $SOUND_FILE)${HOSTNAME}$(cat $CLOCK_FILE)"
}

WORKSPACES_FILE=$(mktemp)
TITLE_FILE=$(mktemp)
SOUND_FILE=$(mktemp)
CLOCK_FILE=$(mktemp)

panel_workspaces $(bspc wm --get-status) > $WORKSPACES_FILE
panel_title "$(xtitle)" > $TITLE_FILE
panel_sound > $SOUND_FILE
panel_clock > $CLOCK_FILE
HOSTNAME=$(panel_hostname)

print_panel

watch_sound &
watch_clock &
watch_workspaces &
watch_title
