#!/bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

source $XDG_CONFIG_HOME/panel/config
source $XDG_CONFIG_HOME/panel/colors

$XDG_CONFIG_HOME/panel/top | lemonbar -p \
	-g "$PANEL_HEIGHT" \
	-u "$PANEL_UNDERLINE" \
	-f "$PANEL_FONT" \
	-f "$PANEL_FONT_FALLBACK" \
	-F "$COLOR_FOREGROUND" \
	-B "$COLOR_BACKGROUND" | while read line; do eval "$line"; done &

wait
