#!/bin/sh

if [ -z ${XDG_CONFIG_HOME+x} ] ; then
	export XDG_CONFIG_HOME="$HOME/.config"
fi

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

source $XDG_CONFIG_HOME/panel/config
source $XDG_CONFIG_HOME/panel/colors

$XDG_CONFIG_HOME/panel/content | lemonbar -p \
	-a 20 \
	-g "$PANEL_HEIGHT" \
	-u "$PANEL_UNDERLINE" \
	-f "$PANEL_FONT" \
	-f "$PANEL_FONT_FALLBACK" \
	-F "$COLOR_FOREGROUND" \
	-B "$COLOR_BACKGROUND" | while read line; do eval "$line"; done &

wait
