#!/bin/bash

if [ "$(pgrep dzen2)" = "" ]
then
	swidth="$(xdpyinfo | grep  -oP " dimensions: +\K[0-9]+(?=x[0-9]+.*)")"
	width="120"
	offset="80"
	(
	echo "^ca(1,killall dzen2 && /usr/local/bin/pixellock)Lock^ca()"
	echo "^ca(1,$XDG_CONFIG_HOME/bspwm/bspwm_killall && bspc quit)Logout^ca()"
	echo "^ca(1,$XDG_CONFIG_HOME/bspwm/bspwm_killall && reboot)Reboot^ca()"
	echo "^ca(1,$XDG_CONFIG_HOME/bspwm/bspwm_killall && poweroff)Poweroff^ca()"

	) | dzen2 -p -x "$((swidth-width-offset))" -y "25" -w "$width" -sa "c" -l 3 -e "onstart=uncollapse,unhide" -fn "Inconsolata" -fg "#f3f3f3" -bg "#93a1a1"
else
	killall dzen2
fi
