#! /bin/sh

xsetroot -cursor_name left_ptr &

sxhkd &

bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config border_width        0
bspc config window_gap         40

bspc config top_padding			35
bspc config right_padding		10
bspc config bottom_padding	10
bspc config left_padding		10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc monitor DVI-I-1 -d o o o o o

bspc monitor DP-2 -d o o o o o
bspc monitor DP-4 -d o o o o o

feh --bg-scale $HOME/.local/share/backgrounds/colorful-triangles-background.jpg

$HOME/.config/panel/panel &

twmnd &

mpd .config/mpd/mpd.conf
mpDris2 &

picom --config ~/.picom.conf &

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1&

nextcloud &
keepassxc &
flatpak run com.belledonnecommunications.linphone --iconified &

fixbar &
