#! /bin/sh

pulseaudio --start

bspc config focus_follows_pointer true

bspc config border_width        0
bspc config window_gap         40

bspc config top_padding			35
bspc config right_padding		10
bspc config bottom_padding	10
bspc config left_padding		10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DP-2 -d o o o o o
bspc monitor DP-4 -d o o o o o

feh --bg-scale ~/Pictures/wallpaper/current.jpg

$XDG_CONFIG_HOME/panel/panel &

twmnd &

compton --backend glx --paint-on-overlay --vsync opengl-swc -b

padevswitch
